config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "invoice#index"
  get '/invoice/new', to: 'invoice#new', as: 'new_invoice'
  post '/invoice', to: 'invoice#create', as: 'create_invoice'
  get 'invoice/:id/edit', to: 'invoice#edit', as: 'edit_invoice'
  patch 'invoice/:id/update', to: 'invoice#update', as: 'update_invoice'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  validates :product_name, :amount, presence: true
  
  after_update :call_job 

  private
  def call_job
    InvoiceDataWorker.perform_async(self.product_name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoice_controller.rb
class InvoiceController < ApplicationController
  
  def index 
    @all_invoices = Invoice.all
  end

  def new
    @invoice = Invoice.new
  end

  def create  
    @invoice = Invoice.new(invoice_params)
    if @invoice.save
      redirect_to root_path
    else
      puts "errors"
    end
  end

  def edit
    @edit_invoice = Invoice.find(params[:id])
  end

  def update
    invoice = Invoice.find(params[:id])
    invoice.update(invoice_params)
    redirect_to root_path
  end

  private

  def invoice_params
    params.require(:invoice).permit(:product_name, :amount)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/views/invoice/edit.html.erb
<h1> Edit Invoice </h1>
<%= form_with model: @edit_invoice, url: update_invoice_path(@edit_invoice.id), method: "patch"  do |f| %>
    <%= f.label :product_name %>
    <%= f.text_field :product_name %>
  
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  
    <%= f.submit %>
  <% end %>

app/views/invoice/index.html.erb
<%= flash[:notice]%>
<h1>Invoice List </h1>
<%= link_to "Create Invoice", new_invoice_path %>

<% @all_invoices.each do |invoice| %>
    <p><%= invoice.product_name %>  => <%= invoice.amount%> <%= link_to "Update Invoice", edit_invoice_path(invoice.id)%> </p>
<% end %>

app/views/invoice/new.html.erb
<h1>Create Invoice </h1>
<%= form_with model: @invoice, url: create_invoice_path do |f| %>
    <%= f.label :product_name %>
    <%= f.text_field :product_name %>
  
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  
    <%= f.submit %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InvoiceTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>